name: VS2026 build

on: push

jobs:
  build:
    name: VS2026
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: ossia/actions/avendish-template@master
        with:
          windows-compiler: 'cl'
          clap: 'true'
          vst3: 'true'
