name: CMake build

on: push

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-26]
    steps:
      - uses: actions/checkout@v4
      - uses: ossia/actions/avendish-template@master
        with:
          clap: 'true'
          vst3: 'true'
          pd: 'true'

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Combine
        shell: bash
        run: |
          find . -name '*.zip'
          mkdir -p output
          find . -name '*.zip' -exec mv {} output/ \;

      - name: Upload
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "output/*"
          branches: "main"
          verbose: true
          prerelease: true
          tag_name: "continuous"
          default_release_name: "Continuous build"
